version: '3'

services:
  master:
    image: locustio/locust
    container_name: locust
    ports:
      - "8089:8089"
      - "5557:5557"
      - "5558:5558"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089